### ISSUE TITLE
01-Data-And-Structures syntax error

### ISSUE THREAD

**Issue by Meiendorf** [becoming/0-java-fundamentals#1]
Where simple arrays are explained there is a line when new element is added to an array, but seems like it can't be done that way.
![image](https://user-images.githubusercontent.com/31164055/55826607-0f40fe00-5b11-11e9-9da7-e02e435a1b5d.png)

**Comment by rodislav** [comment]
please add the link to the file from github repo. 
Thanks.

**Comment by Meiendorf** [comment]
https://github.com/becoming/0-java-fundamentals/blob/026557f2b55e53820eae97ff29f2d4f99abbcbff/01-Data-And-Structures.md#L36

**Comment by rodislav** [comment]
fixed :-)
