### ISSUE TITLE
Static vs. Object call

### ISSUE THREAD

**Issue by SonyKar** [becoming/0-java-fundamentals#2]
It is not quite clear why we should static carefully? Why it is discouraged? When it is best to use static method and when object call?

**Comment by rodislav** [comment]
hello, please add the link to the material that causes the question.

**Comment by SonyKar** [comment]
https://github.com/becoming/0-java-fundamentals/blob/master/07-Simple-Calculator.md

More precisely: https://youtu.be/xpKHcRp9xwU

**Comment by rodislav** [comment]
I've added a explanatory note about the use of static members to the readme file.
If you see a big importance on that I can think about creating this kind of material but this will be most likely a dedicated section with in depth discussions about things somewhere in version 2 of becoming.tech

**Comment by SonyKar** [comment]
Ahah, I like the last statement!

> The detailed use of statics will be described when the material will need it (never - most likely)
