### ISSUE TITLE
Project implementation

### ISSUE THREAD

**Issue by watupzack** [becoming/0-java-fundamentals#6]
I will give an example - Contact List (project), to be more exactly - its implementation
Should I write absolutely unrepeatable my own code?
Or I need just to understand the implementation from the video and just COPY PASTE it to mine IDE?

**Comment by watupzack** [comment]
I'm new to programming, so the only way for me of execution of conditions of the project is author's code :)
I don't think that I can write a working program by myself.
What I should do in that situation, change my thinking form? :)

**Comment by Meiendorf** [comment]
I already asked that question in Slack and this line was added to task description:
https://github.com/becoming/0-java-fundamentals/blob/026557f2b55e53820eae97ff29f2d4f99abbcbff/07-Simple-Calculator.md#L20
So it is up to you, as long as your app meets requirements, you can do whatever you want.

**Comment by rodislav** [comment]
I'll add it as well to the contact list so that it stays clear for other students

**Comment by rodislav** [comment]
https://github.com/becoming/0-java-fundamentals/commit/a4333ac18f4afd556767bde8c9b49df87d3666ac#diff-b5a09d09f844a3e7e9fec913b1b76ea0
