### ISSUE TITLE
Troubles with code(Variables)

### ISSUE THREAD

**Issue by snowtoslow** [becoming/0-java-fundamentals#8]
When I write code from chapter "Variables" (bottom of page) , I faced some bugs , like 
"Error:(5, 13) java: cannot find symbol
  symbol:   class User
  location: class Main" . 
In my opinion  it is necessary to create a class User, but not sure if this is correct.

I will add my code here!)
`Thanks` in advance!)
[https://github.com/snowtoslow/Java-Course](url)

**Comment by rodislav** [comment]
Indeed, you need to create a file `User.java` with a class inside
```java
public class User {
  public User(String name) {
      // usage of the variable name is not mandatory
  }
}
```

**Comment by snowtoslow** [comment]
Okay, thanks a lot :)
